# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        WsunBundle\Entity\Usuarios:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
        #FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:      ROLE_USER
        # ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        user_db:
            entity: { class: WsunBundle\Entity\Usuarios, property: username }

        #fos_userbundle:
          #  id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/admin/login$
            security: false
        
        secured_area:
            pattern:    ^/admin
#            http_basic:
#                realm: "Introduzca Usuario y Contraseña"
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
            logout:
                path: /admin/logout
                target: /
           # pattern: ^/
            #form_login:
               # provider: fos_userbundle
               # csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            #logout:       true
            anonymous:    ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      
        - { path: ^/admin/user/new, role: [ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY] }